dist: trusty
sudo: false
language: node_js
node_js:
- "8"

cache:
  directories:
    - $HOME/.npm
    - node_modules

before_install:
- npm install -g npm@5
- npm install -g codecov
before_script:
- export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
install:
- npm install
script:
- npm run build:apps
- npm run test:coverage
- npm run test:lint
- npm run test:flow
- npm run test:conformance
after_success:
- codecov
