dist: trusty
sudo: false
language: node_js
node_js:
- "8"

cache:
  directories:
    - $HOME/.npm
    - node_modules

before_install:
- npm install -g codecov
install:
- npm install
script:
- npm run test:coverage
- npm run build:apps
- npm run test:lint
- npm run test:flow
- npm run test:conformance
after_success:
- codecov
