environment:
  matrix:
    - nodejs_version: "8"

platform:
  - x64

build: off

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - appveyor-retry npm install

test_script:
  - node --version
  - npm --version
  - npm run build:apps
  - npm run test:coverage
